files:
  - source: /doc/*.rst
    translation: /doc/translations/%two_letters_code%/%original_file_name%
  - source: /src/language/OpenShot/*.pot
    translation: /src/language/OpenShot_%two_letters_code%.po
